# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'projekt_2_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Projekt2DialogBase(object):
    def setupUi(self, Projekt2DialogBase):
        Projekt2DialogBase.setObjectName("Projekt2DialogBase")
        Projekt2DialogBase.resize(531, 467)
        self.button_box = QtWidgets.QDialogButtonBox(Projekt2DialogBase)
        self.button_box.setGeometry(QtCore.QRect(110, 390, 341, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.punkty_lista = QtWidgets.QListWidget(Projekt2DialogBase)
        self.punkty_lista.setGeometry(QtCore.QRect(40, 60, 381, 321))
        self.punkty_lista.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.punkty_lista.setObjectName("punkty_lista")
        self.label = QtWidgets.QLabel(Projekt2DialogBase)
        self.label.setGeometry(QtCore.QRect(30, 10, 171, 51))
        self.label.setObjectName("label")

        self.retranslateUi(Projekt2DialogBase)
        self.button_box.accepted.connect(Projekt2DialogBase.accept) # type: ignore
        self.button_box.rejected.connect(Projekt2DialogBase.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Projekt2DialogBase)

    def retranslateUi(self, Projekt2DialogBase):
        _translate = QtCore.QCoreApplication.translate
        Projekt2DialogBase.setWindowTitle(_translate("Projekt2DialogBase", "projekt2"))
        self.label.setText(_translate("Projekt2DialogBase", "wybierz obiekty :"))
